create table works
(
    id              bigint generated by default as identity
        constraint sora_webui_works_pkey
            primary key,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone default now() not null,
    user_id         varchar,
    input_text            varchar,
    revised_prompt           varchar,
    url           varchar
);

comment on table works is 'works table';

comment on column works.id is 'sequence id';

comment on column works.created_at is 'create time';

comment on column works.updated_at is 'update time';

comment on column works.user_id is 'user uuid';

comment on column works.input_text is 'user input text';

comment on column works.revised_prompt is 'video prompt';

comment on column works.url is 'video url';

alter table works
    owner to "default";

